# Generated by Django 4.1.2 on 2022-10-16 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('data_retirada', models.DateField(null='false')),
                ('data_devolucao', models.DateField(null='True')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livro.livro')),
            ],
        ),
    ]
