# Generated by Django 4.1.2 on 2022-10-18 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0003_livro_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='usuario',
        ),
    ]
